project:
  name: nlu_poc

paths:
  model_dir: nlu/outputs/snips_joint
  asr_model_dir: asr/model/SenseVoiceSmall

asr:
  model_name: sense_voice_small

nlu:
  base_model_name: distilbert-base-uncased
